home:
  path: /
  controller: App\Controller\HomeController::index

property.index:
  path: /biens
  controller: App\Controller\PropertyController::index

property.show:
  path: /biens/{slug}-{id}
  controller: App\Controller\PropertyController::show
  requirements:
      slug: '[a-z0-9\-]*'

admin.property.index:
  path: /admin
  controller: App\Controller\Admin\AdminPropertyController::index

admin.property.new:
  path: /admin/property/create
  controller: App\Controller\Admin\AdminPropertyController::new

admin.property.edit:
  path: /admin/property/{id}
  controller: App\Controller\Admin\AdminPropertyController::edit

admin.property.delete:
  path: /admin/property/delete/{id}
  controller: App\Controller\Admin\AdminPropertyController::delete

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

#index:
#    path: /
#    controller: App\Controller\DefaultController::index